from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict
from backend.app.schemas.rag import RAGContextResponse


class PatientInput(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "pregnancies": 1,
                "glucose": 115.0,
                "blood_pressure": 72.0,
                "skin_thickness": 20.0,
                "insulin": 80.0,
                "bmi": 26.5,
                "diabetes_pedigree": 0.45,
                "age": 32.0
            }
        }
    )

    pregnancies: int = Field(
        default=1,
        ge=0,
        le=25,
        description="Number of times pregnant"
    )
    glucose: float = Field(
        default=115.0,
        ge=10.0,
        le=500.0,
        description="2-Hour plasma glucose concentration (mg/dL)"
    )
    blood_pressure: float = Field(
        default=72.0,
        ge=20.0,
        le=250.0,
        description="Diastolic blood pressure (mm Hg)"
    )
    skin_thickness: float = Field(
        default=20.0,
        ge=0.0,
        le=120.0,
        description="Triceps skin fold thickness (mm)"
    )
    insulin: float = Field(
        default=80.0,
        ge=0.0,
        le=1000.0,
        description="2-Hour serum insulin (mu U/ml)"
    )
    bmi: float = Field(
        default=26.5,
        ge=10.0,
        le=80.0,
        description="Body mass index (weight in kg / (height in m)²)"
    )
    diabetes_pedigree: float = Field(
        default=0.45,
        ge=0.0,
        le=3.5,
        description="Diabetes pedigree function score"
    )
    age: float = Field(
        default=32.0,
        ge=1.0,
        le=125.0,
        description="Patient age in years"
    )


class PredictionResult(BaseModel):
    prediction: int = Field(..., description="Binary classification (0: No Diabetes, 1: Diabetes)")
    prediction_label: str = Field(..., description="Human-readable classification outcome")
    probability_diabetes: float = Field(..., description="Model calculated probability of diabetes (%)")
    probability_no_diabetes: float = Field(..., description="Model calculated probability of non-diabetes (%)")
    risk_level: str = Field(..., description="Qualitative risk tier: Low, Moderate, Elevated")


class BiomarkerComparison(BaseModel):
    biomarker: str
    feature_key: str
    entered_value: float
    unit: str
    reference_interval: str
    status: str  # "Normal", "Elevated", "Borderline", "Informational"
    clinical_note: str


class AssessmentResponse(BaseModel):
    id: str = Field(..., description="Anonymized evaluation identifier, e.g. PT-2024-8192")
    timestamp: str = Field(..., description="ISO 8601 evaluation timestamp")
    patient_inputs: PatientInput
    prediction: PredictionResult
    biomarker_comparisons: List[BiomarkerComparison] = Field(default_factory=list)
    rag_context: RAGContextResponse
    clinical_disclaimer: str = Field(
        default=(
            "⚕️ DECISION SUPPORT DISCLAIMER: This assessment is generated by an educational machine learning model "
            "(DecisionTreeClassifier) and clinical reference retrieval engine. It is strictly an AI-assisted screening "
            "and educational tool. It does NOT constitute a clinical diagnosis, medical evaluation, or prescription. "
            "Always consult a licensed medical professional for clinical diagnosis and healthcare guidance."
        )
    )


class AssessmentHistoryItem(BaseModel):
    id: str
    timestamp: str
    age: float
    glucose: float
    bmi: float
    blood_pressure: float
    prediction: int
    prediction_label: str
    probability_diabetes: float
    risk_level: str
